hostname: rke1

rancher:
  network:
    interfaces:
      eth*:
       dhcp: false
      eth0:
       address: 192.168.10.138/24
       gateway: 192.168.10.3
    dns:
     nameservers:
      - 8.8.8.8

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCjqurovSVudx4XDzCpu6nhI4OBx6DvDP3HTXHx4CH93dsgkmG9GgvdIoXwfkyVHeyFx7bI2thGSjTXGN37K6A5uoDpsgxjr/DwLxDsOWCD6CsTznq9jdj+3HNGsv/TKg2eGjAlfi4PiF39QkCN/n+Mx1f3yJ2+zgbaVqbG4LKWosn3kAfQk+ROLVm16JHxxavghGrI263HRd2hQsQPPfC6UmhA1JDf/X+hT4xHtE0eeLAcAfM+GUgls/XfED8PRUHOE4uh8rPKkmdY6QwtuDPjBGlgHMeRa2z8Ag/1Fz0/jrJDY0NWvLS+/f61EFgW9TOKU2rxzic11RZRqpXWQO7B john@mx
  

